version: '3.8'
services:
  mysql-dev:
    image: mysql:8.0
    container_name: uxia-server-mysql
    environment:
      MYSQL_DATABASE: UxiaDDBB
      MYSQL_USER: super
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3308:3306"
    volumes:
      - mysql-dev-data:/var/lib/mysql
    restart: always
volumes:
  mysql-dev-data:
